// Full മസ്ജിദ് അഫിലിയേഷൻ അപേക്ഷ, transcribed from masjid-affliation.md (34 questions, 4 pages).
// Kept in its own module because it is far larger than the other seeded forms.
// District/Area selects carry empty options — the renderer fills them from master-data
// for the ids named in roleMapping.

module.exports = {
  formType: "affiliation",
  title: "മസ്ജിദ് അഫിലിയേഷനുള്ള അപേക്ഷ",
  description: "Masjid Council Kerala — Mosque affiliation application",
  enabled: true,
  isPublished: true,
  publishedAt: new Date(),
  instructions: [
    { id: 1, text: "പള്ളിയുടെ പൂർണ വിവരങ്ങൾ കൈയിൽ കരുതുക — വരവ്-ചെലവ് കണക്കുകൾ, ജീവനക്കാരുടെ വിവരങ്ങൾ, ഭാരവാഹികളുടെ ഫോൺ നമ്പറുകൾ.", order: 1 },
    { id: 2, text: "അപേക്ഷ സമർപ്പിക്കേണ്ടത് മാനേജിംഗ് കമ്മിറ്റി / ട്രസ്റ്റ് യോഗ തീരുമാനപ്രകാരമാണ്.", order: 2 },
    { id: 3, text: "ഒപ്പും സീലും ഉള്ള പ്രഖ്യാപന പേജിന്റെ കോപ്പി അവസാന ഘട്ടത്തിൽ അപ്‌ലോഡ് ചെയ്യണം.", order: 3 },
  ],
  roleMapping: { districtFieldId: 6, areaFieldId: 12, phoneFieldId: 8, nameFieldId: 1 },
  pages: [
    {
      id: 1,
      title: "പള്ളിയുടെ അടിസ്ഥാന വിവരങ്ങൾ",
      order: 1,
      fields: [
        { id: 1, label: "പള്ളിയുടെ പേര്", type: "text", required: true, enabled: true },
        { id: 2, label: "പള്ളിയുടെ സ്വഭാവം", type: "radio", required: true, enabled: true, options: ["മഹല്ല് പള്ളി", "ജുമുഅത്ത് പള്ളി", "നമസ്കാര പള്ളി", "ടൗൺ പള്ളി"] },
        { id: 3, label: "മഹല്ലിന്റെ സ്വഭാവം", type: "radio", required: true, enabled: true, options: ["പൂർണ മഹല്ല്", "ഭാഗിക മഹല്ല്", "സംയുക്ത മഹല്ല്"] },
        { id: 4, label: "പള്ളി പ്രവർത്തനമാരംഭിച്ച വർഷം", type: "number", required: true, enabled: true, validation: { min: 1800, max: 2100 } },
        { id: 5, label: "പൂർണ വിലാസം", type: "textarea", required: true, enabled: true },
        { id: 6, label: "ജില്ല", type: "select", required: true, enabled: true, options: [] },
        { id: 7, label: "പിൻകോഡ്", type: "number", required: true, enabled: true },
        { id: 8, label: "ഫോൺ (കോഡ് സഹിതം)", type: "phone", required: true, enabled: true },
        { id: 9, label: "ഇ-മെയിൽ", type: "email", required: false, enabled: true },
        { id: 10, label: "വെബ്സൈറ്റ്", type: "text", required: false, enabled: true },
        { id: 11, label: "ജമാഅത്തെ ഇസ്ലാമി ഘടകം", type: "text", required: false, enabled: true },
        { id: 12, label: "ഏരിയ", type: "select", required: true, enabled: true, options: [] },
        {
          id: 13,
          label: "പള്ളിയോടനുബന്ധിച്ച ഇതര സ്ഥാപനങ്ങൾ",
          type: "checkbox",
          required: false,
          enabled: true,
          options: ["മദ്രസ", "റീഡിംഗ് റൂം", "ലൈബ്രറി", "ഡിജിറ്റൽ ലൈബ്രറി", "ഹോളിഡേ മദ്രസ", "ഖുർആൻ സ്റ്റഡി സെന്റർ", "സകാത്ത് സെൽ", "പലിശരഹിത നിധി", "നോട്ടീസ് ബോർഡ്", "വനിതാ വേദി", "സേവന വേദി"],
        },
        { id: 14, label: "ഖബറിസ്ഥാൻ ഉണ്ടോ?", type: "yesno", required: true, enabled: true },
        { id: 15, label: "ഖബറിസ്ഥാന്റെ വിസ്തീർണം", type: "text", required: false, enabled: true, conditionalLogic: { field: 14, operator: "equals", value: "yes", action: "show" } },
        { id: 16, label: "പള്ളിയിൽ എത്ര പേർക്ക് നമസ്കരിക്കാം?", type: "number", required: true, enabled: true },
        { id: 17, label: "പള്ളിയുടെ വിസ്തീർണം", type: "text", required: false, enabled: true },
        { id: 18, label: "ജുമുഅക്ക് പങ്കെടുക്കുന്ന പുരുഷന്മാരുടെ ശരാശരി എണ്ണം", type: "number", required: true, enabled: true },
        { id: 19, label: "ജുമുഅക്ക് പങ്കെടുക്കുന്ന സ്ത്രീകളുടെ ശരാശരി എണ്ണം", type: "number", required: false, enabled: true },
        { id: 20, label: "പള്ളിയുടെ സ്ഥാവര-ജംഗമ സ്വത്തുക്കൾ", type: "textarea", required: false, enabled: true },
        { id: 21, label: "വരുമാന മാർഗങ്ങൾ", type: "textarea", required: false, enabled: true },
        { id: 22, label: "പ്രതിമാസ ചെലവ്", type: "number", required: false, enabled: true },
        { id: 23, label: "വരവ്-ചെലവ് കണക്കുകൾ കൃത്യമായി ഓഡിറ്റ് ചെയ്യാറുണ്ടോ?", type: "yesno", required: false, enabled: true },
        {
          id: 24,
          label: "സൂക്ഷിക്കുന്ന രേഖകൾ",
          type: "checkbox",
          required: false,
          enabled: true,
          options: ["അസറ്റ് രജിസ്റ്റർ", "വരിസംഖ്യ റസീപ്റ്റ്", "പേയ്മെന്റ് വൗച്ചർ", "സാലറി റസീപ്റ്റ്", "ജനന/മരണ രജിസ്റ്റർ", "വിവാഹ രജിസ്റ്റർ", "വിവാഹ മോചന രജിസ്റ്റർ", "സ്റ്റാഫ് പേറോൾ", "ഇൻവാഡ് / ഔട്ട്‌വാഡ് ഫയൽ", "ഖബർ രജിസ്റ്റർ", "ഡേ ബുക്ക്"],
        },
        { id: 25, label: "കഴിഞ്ഞ ഒരു വർഷത്തെ മൊത്തം വരവ്", type: "number", required: false, enabled: true },
        { id: 26, label: "കഴിഞ്ഞ ഒരു വർഷത്തെ മൊത്തം ചെലവ്", type: "number", required: false, enabled: true },
        {
          id: 27,
          label: "മഹല്ലിന്റെ / പള്ളിയുടെ മേൽനോട്ടത്തിൽ നടക്കുന്ന ജനസേവന സംരംഭങ്ങൾ",
          type: "checkbox",
          required: false,
          enabled: true,
          options: ["പലിശരഹിത നിധി", "അയൽക്കൂട്ടം", "അഗതി മന്ദിരങ്ങൾ / യതീംഖാനകൾ", "ബ്ലഡ് ബാങ്ക്", "പാലിയേറ്റീവ് പ്രവർത്തനങ്ങൾ", "തൊഴിൽ പരിശീലനങ്ങൾ", "മെഡിക്കൽ ഹെൽപ്", "കൗൺസിലിംഗ്", "ഡി-അഡിക്ഷൻ സെന്റർ", "സ്കോളർഷിപ്പ്", "കരിയർ ഹെൽപ് സെന്റർ"],
        },
        { id: 28, label: "ജനസേവന സംരംഭങ്ങൾ — മറ്റുള്ളവ", type: "text", required: false, enabled: true },
      ],
    },
    {
      id: 2,
      title: "സമിതികളും ഭാവി പദ്ധതികളും",
      order: 2,
      fields: [
        {
          id: 29,
          label: "മഹല്ലിന്റെ / പള്ളിയുടെ മേൽനോട്ടത്തിൽ നടക്കുന്ന സമിതികൾ / പ്രവർത്തനങ്ങൾ",
          type: "checkbox",
          required: false,
          enabled: true,
          options: ["മസ്വലഹത്ത് / പ്രശ്നപരിഹാര സമിതി", "കരിയർ ഗൈഡൻസ്", "ഹെൽപ് ഡെസ്ക്", "അഡോളസൻസ് ബോധവത്കരണം", "ആരോഗ്യ ബോധവത്കരണം", "വിദ്യാഭ്യാസ സമിതി", "സാമ്പത്തിക ചിട്ട ബോധവത്കരണം", "കുടുംബ ശാക്തീകരണ പദ്ധതികൾ"],
        },
        { id: 30, label: "മറ്റ് സാമൂഹ്യ-സാംസ്കാരിക പദ്ധതികൾ / പരിപാടികൾ", type: "textarea", required: false, enabled: true },
        { id: 31, label: "മഹല്ലിൽ നടപ്പിലാക്കാൻ ഉദ്ദേശിക്കുന്ന പദ്ധതികൾ / പ്രവർത്തനങ്ങൾ", type: "textarea", required: false, enabled: true },
        { id: 32, label: "പ്രായോഗിക പരിശീലനം ആവശ്യമുള്ള പ്രവർത്തനങ്ങളുടെ വിവരണം", type: "textarea", required: false, enabled: true },
        { id: 33, label: "സർക്കാർ / സർക്കാറേതര സഹായങ്ങൾ ലഭ്യമാകുന്നുണ്ടോ?", type: "yesno", required: false, enabled: true, helpText: "ഉദാ: വഖഫ് ബോർഡ് സഹായം, മദ്രസ മോഡേണൈസേഷൻ ഫണ്ട്, സ്കോളർഷിപ്പുകൾ, ജീവനക്കാരുടെ പെൻഷൻ പദ്ധതി, വിവാഹ ധനസഹായം, സാമൂഹ്യക്ഷേമ വകുപ്പിന്റെ സഹായങ്ങൾ" },
        { id: 34, label: "സഹായങ്ങളുടെ വിവരണം", type: "textarea", required: false, enabled: true, conditionalLogic: { field: 33, operator: "equals", value: "yes", action: "show" } },
        { id: 35, label: "മഹല്ല് സർവേ നടത്തിയിട്ടുണ്ടോ?", type: "yesno", required: false, enabled: true },
        { id: 36, label: "നിലവിൽ നടന്നുകൊണ്ടിരിക്കുന്ന നിർമ്മാണ പ്രവർത്തനങ്ങൾ", type: "textarea", required: false, enabled: true },
        { id: 37, label: "സമീപഭാവിയിൽ നടത്താനുദ്ദേശിക്കുന്ന നിർമ്മാണ, വികസന പ്രവർത്തനങ്ങൾ", type: "textarea", required: false, enabled: true },
      ],
    },
    {
      id: 3,
      title: "വികസനവും ഭരണ സമിതിയും",
      order: 3,
      fields: [
        { id: 38, label: "പ്രദേശത്തെ മഹല്ലിന്റെ വികസന സാധ്യതകൾ", type: "textarea", required: false, enabled: true },
        { id: 39, label: "പള്ളി പരിപാലനവുമായി ബന്ധപ്പെട്ട് അനുഭവിക്കുന്ന പ്രയാസങ്ങൾ", type: "textarea", required: false, enabled: true },
        { id: 40, label: "പള്ളിയിലും അനുബന്ധ സ്ഥാപനങ്ങളിലും പൊതുജന സഹകരണം", type: "radio", required: false, enabled: true, options: ["മികച്ചത്", "തൃപ്തികരം", "തീരെ കുറവ്"] },
        { id: 41, label: "പള്ളിയിലും അനുബന്ധ സ്ഥാപനങ്ങളിലും ഗുണകാംക്ഷികളുടെ പങ്കാളിത്തം", type: "radio", required: false, enabled: true, options: ["മികച്ചത്", "തൃപ്തികരം", "തീരെ കുറവ്"] },
        { id: 42, label: "മഹല്ല് അഡ്മിനിസ്ട്രേഷൻ (ഡാറ്റാ ഹാൻഡ്ലിംഗ്) സോഫ്റ്റ്‌വെയർ ഉപയോഗിക്കുന്നുണ്ടോ?", type: "yesno", required: false, enabled: true },
        { id: 43, label: "മഹല്ല് അംഗങ്ങൾക്കിടയിൽ ആശയവിനിമയത്തിന് ന്യൂ മീഡിയ ഉപയോഗിക്കാറുണ്ടോ?", type: "yesno", required: false, enabled: true, helpText: "വാട്സ്ആപ്പ്, ഫേസ്ബുക്ക്, എസ്.എം.എസ് തുടങ്ങിയവ" },
        { id: 44, label: "മാനേജിംഗ് കമ്മിറ്റിയുടെ പേര്", type: "text", required: true, enabled: true },
        { id: 45, label: "കമ്മിറ്റിയുടെ ഘടന", type: "select", required: false, enabled: true, options: ["ട്രസ്റ്റ്", "അസോസിയേഷൻ കമ്മിറ്റി", "മുതവല്ലി"] },
        {
          id: 46,
          label: "ഭാരവാഹികളുടെ പേരും വിലാസവും",
          type: "row",
          required: true,
          enabled: true,
          columns: 4,
          columnTitles: ["പദവി", "പേര് / വിലാസം", "മൊബൈൽ", "ഇ-മെയിൽ"],
          rows: 2,
          firstColumnHeader: "ക്രമ നമ്പർ",
          allowAddRows: true,
          helpText: "പ്രസിഡന്റ് / ചെയർമാൻ, സെക്രട്ടറി എന്നിവരുടെ വിവരങ്ങൾ നിർബന്ധം",
        },
        {
          id: 47,
          label: "മസ്ജിദ് നടത്തിപ്പിന് രൂപീകരിച്ച സബ് കമ്മിറ്റി ഭാരവാഹികൾ",
          type: "row",
          required: false,
          enabled: true,
          columns: 4,
          columnTitles: ["പദവി", "പേര് / വിലാസം", "മൊബൈൽ", "ഇ-മെയിൽ"],
          rows: 2,
          firstColumnHeader: "ക്രമ നമ്പർ",
          allowAddRows: true,
        },
      ],
    },
    {
      id: 4,
      title: "ജീവനക്കാരും പ്രഖ്യാപനവും",
      order: 4,
      fields: [
        {
          id: 48,
          label: "ഖത്വീബ് ഉൾപ്പെടെ ജീവനക്കാരെ സംബന്ധിച്ച വിവരങ്ങൾ",
          type: "row",
          required: false,
          enabled: true,
          columns: 6,
          columnTitles: ["പേര്", "വയസ്", "സ്ഥാനം", "യോഗ്യത", "ശമ്പളം", "റിമാർക്സ്"],
          rows: 5,
          firstColumnHeader: "ക്രമ നമ്പർ",
          allowAddRows: true,
        },
        { id: 49, label: "അന്യ സംസ്ഥാന ജീവനക്കാർ ഉണ്ടോ?", type: "yesno", required: false, enabled: true },
        { id: 50, label: "അന്യ സംസ്ഥാന ജീവനക്കാരെ നിയമിക്കുമ്പോൾ ആവശ്യമായ നടപടിക്രമങ്ങൾ പാലിക്കാറുണ്ടോ / രേഖകൾ സൂക്ഷിക്കാറുണ്ടോ?", type: "yesno", required: false, enabled: true, conditionalLogic: { field: 49, operator: "equals", value: "yes", action: "show" } },
        { id: 51, label: "അഫിലിയേഷൻ അപേക്ഷ / പ്രഖ്യാപനം", type: "title", required: false, enabled: true },
        { id: 52, label: "യോഗം ചേർന്ന തീയതി", type: "date", required: true, enabled: true },
        { id: 53, label: "ട്രസ്റ്റ് / കമ്മിറ്റി / അസോസിയേഷന്റെ പേര്", type: "text", required: true, enabled: true },
        {
          id: 54,
          label: "പ്രഖ്യാപനം",
          type: "checkbox",
          required: true,
          enabled: true,
          options: ["സമ്മതിക്കുന്നു"],
          helpText: "മേൽ യോഗ തീരുമാനപ്രകാരം ഈ പള്ളിയെ മസ്ജിദ് കൗൺസിൽ കേരളയിൽ അഫിലിയേറ്റ് ചെയ്യണമെന്ന് അപേക്ഷിക്കുന്നു. മസ്ജിദ് കൗൺസിലിന്റെ മാർഗനിർദേശങ്ങൾ അനുസരിച്ച് പ്രവർത്തിച്ചുകൊള്ളാമെന്ന് സ്ഥാപനത്തിനുവേണ്ടി ഞാൻ പ്രതിജ്ഞ ചെയ്യുന്നു.",
        },
        { id: 55, label: "അപേക്ഷ സമർപ്പിക്കുന്ന തീയതി", type: "date", required: true, enabled: true },
        { id: 56, label: "സ്ഥലം", type: "text", required: true, enabled: true },
        { id: 57, label: "അപേക്ഷകന്റെ പേര്", type: "text", required: true, enabled: true },
        { id: 58, label: "പദവി", type: "select", required: true, enabled: true, options: ["പ്രസിഡന്റ്", "ചെയർമാൻ", "സെക്രട്ടറി"] },
        { id: 59, label: "ഒപ്പും സീലും ഉള്ള പ്രഖ്യാപന പേജ്", type: "file", required: false, enabled: true, helpText: "PDF/JPG, പരമാവധി 5 MB" },
      ],
    },
  ],
};
